package Modell;


import javax.print.DocFlavor;
import java.sql.*;

public class Database {

    private static Database databaseInstance=null;


    Connection conn = null;
    Statement createStatement = null;
    DatabaseMetaData dbmd = null;


    private Database() {

        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@codd.inf.unideb.hu:1521:ora12c", "U_C4NVNX", "rolcsi89");
        } catch (Exception ex) {
            System.out.println("hiba a onnectionnál");
            System.out.println(ex);
        }


        if (conn != null){
            try {
                createStatement = conn.createStatement();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }


        try {
            dbmd = conn.getMetaData();
        } catch (SQLException ex) {
            System.out.println(ex);
        }

        try {
            ResultSet rs = dbmd.getTables(null, "APP", "USERS", null);
            if(!rs.next())
            {
                createStatement.execute("" +
                        "create table " +
                        "Users(" +
                        "ID INT GENERATED BY DEFAULT ON NULL AS IDENTITY," +
                        "username varchar2(20) NOT NULL," +
                        "password varchar2(20) NOT NULL," +
                        "bought_tickets number DEFAULT 0," +
                        "winner_tickets number DEFAULT 0," +
                        "credit number DEFAULT 1000," +
                        "credit_used_up number DEFAULT 0," +
                        "credit_won number DEFAULT 0," +
                        "credit_lost number DEFAULT 0)");
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    public static Database getDatabaseInstance() {
        if (databaseInstance==null) {
            return new Database();
        } else {
            return databaseInstance;
        }
    }

    public String authUser(String username) {
        String query="select * from users where username='"+username+"'";
        try {

            ResultSet rs = createStatement.executeQuery(query);

            if(rs.next()) {
                return "USER_EXISTS";
            } else {
                return "USER_DOESNT_EXISTS";
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return "DB_PROBLEM";
        }
    }

    public String addUser(String username, String password) {
        try {
            PreparedStatement stmt=conn.prepareStatement("" +
                    "INSERT INTO USERS (username, password) VALUES (?,?)");
            stmt.setString(1,username);
            stmt.setString(2,password);
            stmt.execute();
        } catch (SQLException e) {
            e.printStackTrace();
            return "FAILED_SIGNUP";
        }

        return "SUCCESSFULLY_SIGNUP";
    }

    public String login(String username,String password) {

        String query="select * from users where username='"+username+"' and password='"+password+"'";
        try {
            ResultSet rs = createStatement.executeQuery(query);

            if(rs.next()) {
                return "SUCCES_LOGIN";
            } else {
                return "BAD_PASSWORD";
            }


        } catch (Exception e) {
            System.out.println("DB PROBLEM?"+e);
            return "DB_PROBLEM";
        }

    }


}
