package Modell;


import javax.print.DocFlavor;
import java.sql.*;

public class Database {

    private static Database databaseInstance=null;


    Connection conn = null;
    Statement createStatement = null;
    DatabaseMetaData dbmd = null;


    private Database() {

        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@codd.inf.unideb.hu:1521:ora12c", "U_C4NVNX", "rolcsi89");
            System.out.println("efut");
        } catch (Exception ex) {
            System.out.println("hiba a onnectionnál");
            System.out.println(ex);
        }


        if (conn != null){
            try {
                createStatement = conn.createStatement();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }


        try {
            dbmd = conn.getMetaData();
        } catch (SQLException ex) {
            System.out.println(ex);
        }

        try {
            ResultSet rs = dbmd.getTables(null, "APP", "USERS", null);
            if(!rs.next())
            {
                createStatement.execute("" +
                        "create table " +
                        "Users(" +
                        "ID INT GENERATED BY DEFAULT ON NULL AS IDENTITY," +
                        "username varchar2(20) NOT NULL," +
                        "password varchar2(20) NOT NULL," +
                        "bought_tickets number DEFAULT 0," +
                        "winner_tickets number DEFAULT 0," +
                        "credit number DEFAULT 1000," +
                        "credit_used_up number DEFAULT 0," +
                        "credit_won number DEFAULT 0," +
                        "credit_lost number DEFAULT 0)");
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    public static Database getDatabaseInstance() {
        if (databaseInstance==null) {
            return new Database();
        } else {
            return databaseInstance;
        }
    }

    public boolean authUser(String username) {
        Boolean userExists=null;
        try {
            PreparedStatement stmt=conn.prepareStatement(
                    "select *" +
                    "from users" +
                    "where username=?;");
            stmt.setString(1,username);
            ResultSet rs=stmt.executeQuery();

            if(rs.next()) {
                userExists = true;
            } else {
                userExists=false;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return userExists;
    }

    public String signUp(String username, String password) {
        try {
            PreparedStatement stmt=conn.prepareStatement("" +
                    "INSERT INTO USERS (username, password) VALUES (?,?)");
            stmt.setString(0,username);
            stmt.setString(1,password);
            boolean succ=stmt.execute();
            if (succ) {
                return "SUCCESSFULLY_SIGNUP";
            } else {
                return "FAILED_SIGNUP";
            }

        } catch (SQLException e) {
            e.printStackTrace();
            return "FAILED_SIGNUP";
        }


    }

    public String login(String username,String password) {
            boolean userExists=authUser(username);
            try {

                if (userExists) {
                    PreparedStatement stmt=conn.prepareStatement(
                            "select *" +
                                    "from users" +
                                    "where username=? and password=?;");
                    stmt.setString(0,username);
                    stmt.setString(1,password);
                    ResultSet rs=stmt.executeQuery();
                    if(rs.next()) {
                        return "SUCCES_LOGIN";
                    } else {
                        return "BAD_PASSWORD";
                    }
                } else {
                    return "USERNAME_NOT_EXISTS";
                }

            } catch (Exception e) {
                return "DB_PROBLEM";
            }

    }
}
